### ISSUE TITLE
有的依赖不能用，请问这个要怎么解决

### ISSUE THREAD

**Issue by codee-vip** [18380438200/MvvmFrame#1]
![image](https://user-images.githubusercontent.com/20723516/114992570-78f8fd00-9ecd-11eb-9a75-00fd44ee3b62.png)
有的依赖不能用，请问这个要怎么解决啊

**Comment by codee-vip** [comment]
> `https://github.com/running-libo/Eyepetizer/tree/4b1ab85ab5d8d910e458390f1b05dd0ea785ecf7`
使用上面的版本，依赖显示正常
![image](https://user-images.githubusercontent.com/20723516/114999188-325ad100-9ed4-11eb-8a48-daa72c4b81c1.png)
但是，启动后控制台报错：
![image](https://user-images.githubusercontent.com/20723516/114999674-a7c6a180-9ed4-11eb-9a33-7450cf15b6e5.png)
app里都是空数据
![image](https://user-images.githubusercontent.com/20723516/114999561-8cf42d00-9ed4-11eb-9278-021f31de2bea.png)
下载下来第一次启动会报错：
![image](https://user-images.githubusercontent.com/20723516/115002234-1442a000-9ed7-11eb-9cf1-0312332fee94.png)
在app的gradle中加入上图的提示信息就可以了：
![image](https://user-images.githubusercontent.com/20723516/115002335-350af580-9ed7-11eb-947d-d413d7006c56.png)

**Comment by running-libo** [comment]
在各个模块的maven.properties模块下，把远程依赖MAVEN=true改为false，再同步一下gradle就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "running-libo/Eyepetizer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月16日(星期五) 下午4:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [running-libo/Eyepetizer] 有的依赖不能用，请问这个要怎么解决 (#1)





  
https://github.com/running-libo/Eyepetizer/tree/4b1ab85ab5d8d910e458390f1b05dd0ea785ecf7
 使用上面的版本，依赖显示正常
 
 但是，启动后控制台报错：
 
 app里都是空数据

**Comment by codee-vip** [comment]
![image](https://user-images.githubusercontent.com/20723516/115002672-9cc14080-9ed7-11eb-99e2-d9a935c94d05.png)
运行起来了

个人中心和登录只有页面[/捂脸]

**Comment by codee-vip** [comment]
> 在各个模块的maven.properties模块下，把远程依赖MAVEN = true更改为false，再同步一下gradle就可以了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "running-libo/Eyepetizer" ***@***.***&gt;; 发送时间:&nbsp;2021年4月16日(星期五) 下午4:55 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [running-libo/Eyepetizer] 有的依赖不能用，请问这个要怎么解决 (#1) https://github.com/running-libo/Eyepetizer/tree/4b1ab85ab5d8d910e458390f1b05dd0ea785ecf7 使用上面的版本，依赖显示正常 但是，启动后控制台报错： app里都是空数据 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 在各个模块的maven.properties模块下，把远程依赖MAVEN = true更改为false，再同步一下gradle就可以了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "running-libo/Eyepetizer" ***@***.***&gt;; 发送时间:&nbsp;2021年4月16日(星期五) 下午4:55 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [running-libo/Eyepetizer] 有的依赖不能用，请问这个要怎么解决 (#1) https://github.com/running-libo/Eyepetizer/tree/4b1ab85ab5d8d910e458390f1b05dd0ea785ecf7 使用上面的版本，依赖显示正常 但是，启动后控制台报错： app里都是空数据 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
